### PR TITLE
Replace the bash startup script with a Python one

### PR DESCRIPTION
**Pull request by aggelgian**
The bash startup script is replaced with a Python v2.x one.
You can now test `foo:bar/1` with

    ./cuter foo bar '[ok]'

Set the depth to `42` with the `-d` flag.

    ./cuter foo bar '[ok]' -d 42

You can now test MFAs from loaded modules, e.g. `lists` from stdlib, with the `-l` flag.

    ./cuter lists append '[[]]' -l

All the options are available with

    ./cuter --help

P.S. Arguments and options can be intermixed according to the GNU scanning mode.

    ./cuter -d 2 -v -c lists reverse '[[1]]' -l -p 4 -s 4

P.S.2 Updated with renaming `cuter.py` to `cuter`

### CODE REVIEW

**Comment by kostis** [comment]
A minor comment is that I do not really see the need/reason for the `.py` extension of the script.  It should be taken out.

Also, in an environment without `ERL_LIBS` set, which is my default environment, all my attempts to use it result in:
<pre>Fatal Error: cannot concatenate 'str' and 'NoneType' objects</pre>

**Comment by aggelgian** [comment]
Both issues are fixed. It should work properly now.

**Comment by kostis** [comment]
Interrupting the script with Cntr-C spits out quite a bit of (mostly irrelevant) info:
<pre>$ ./cuter otp_int obsolete '[erlang, length, 1]'
Testing otp_int:obsolete/3 ...
.............^C
BREAK: (a)bort (c)ontinTraceback (most recent call last):
ue (p)roc in  File "./cuter", line 122, in <module>
fo (i)nfo (l)oaded
       (v)ersion (k)ill (D)b-tables (d)istribution
    main(sys.argv[1:])
  File "./cuter", line 73, in main
    sys.exit(runCuter(cmd))
  File "./cuter", line 98, in runCuter
    return subp.call(cmd, shell=True)
  File "/usr/lib/python2.7/subprocess.py", line 522, in call
    return Popen(*popenargs, **kwargs).wait()
  File "/usr/lib/python2.7/subprocess.py", line 1384, in wait
    pid, sts = _eintr_retry_call(os.waitpid, self.pid, 0)
  File "/usr/lib/python2.7/subprocess.py", line 476, in _eintr_retry_call
    return func(*args)
KeyboardInterrupt</pre>
It would be better if we can suppress that.

**Comment by aggelgian** [comment]
Now just suppressing the Python traceback after interrupting.

**Pull request merged**
